$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: ${{DEPLOY_NAME}}
endpoint_name: ${{ENDPOINT_NAME}}
model:
  image: ${{IMAGE_URI}}
environment_variables:
  HANDLER: "${{HANDLER}}"
instance_type: ${{INSTANCE_TYPE}}
instance_count: ${{INSTANCE_COUNT}}
request_settings:
  request_timeout_ms: ${{REQUEST_TIMEOUT_MS}}
  max_concurrent_requests_per_instance: ${{MAX_CONCURRENT_REQUESTS}}
liveness_probe:
  initial_delay: 30
  period: 10
  timeout: 2
  success_threshold: 1
  failure_threshold: 3
readiness_probe:
  initial_delay: 30
  period: 10
  timeout: 2
  success_threshold: 1
  failure_threshold: 3
