name: Azure Login

on:
  workflow_dispatch:
    inputs:
      resource-group:
        description: 'Azure resource group to use'
        required: false
        type: string
      location:
        description: 'Azure location (region)'
        required: false
        type: string
        default: 'eastus'

permissions:
  id-token: write
  contents: read

jobs:
  azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login with AZURE_CREDENTIALS
        if: env.AZURE_CREDENTIALS != ''
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login with separate credentials
        if: env.AZURE_CREDENTIALS == '' && env.AZURE_CLIENT_ID != ''
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set environment variables
        run: |
          echo "Setting up Azure environment variables"
          
          # Set subscription ID
          SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          echo "AZURE_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}" >> $GITHUB_ENV
          echo "Connected to Azure subscription: $(az account show --query name -o tsv) (${SUBSCRIPTION_ID})"
          
          # Set resource group
          if [[ -n "${{ inputs.resource-group }}" ]]; then
            echo "AZURE_RESOURCE_GROUP=${{ inputs.resource-group }}" >> $GITHUB_ENV
            echo "Using resource group: ${{ inputs.resource-group }}"
          elif [[ -n "${{ secrets.AZURE_RESOURCE_GROUP }}" ]]; then
            echo "AZURE_RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}" >> $GITHUB_ENV
            echo "Using resource group from secrets: ${{ secrets.AZURE_RESOURCE_GROUP }}"
          fi
          
          # Set location
          if [[ -n "${{ inputs.location }}" ]]; then
            echo "AZURE_LOCATION=${{ inputs.location }}" >> $GITHUB_ENV
            echo "Using location: ${{ inputs.location }}"
          elif [[ -n "${{ secrets.AZURE_LOCATION }}" ]]; then
            echo "AZURE_LOCATION=${{ secrets.AZURE_LOCATION }}" >> $GITHUB_ENV
            echo "Using location from secrets: ${{ secrets.AZURE_LOCATION }}"
          else
            echo "AZURE_LOCATION=eastus" >> $GITHUB_ENV
            echo "Using default location: eastus"
          fi

      - name: Verify Azure Connection
        run: |
          echo "Verifying Azure connection..."
          az account show
          echo "Azure login successful"