name: Deploy Components

on:
  push:
    branches: [ main ]
    paths:
      - 'components/**'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      component-path:
        description: 'Path to the component to deploy (leave empty for all)'
        required: false
        type: string
      resource-group:
        description: 'Azure resource group'
        required: false
        type: string
      subscription-id:
        description: 'Azure subscription ID (leave empty to use default from AZURE_CREDENTIALS)'
        required: false
        type: string

jobs:
  azure-login:
    uses: ./.github/workflows/azure-auth.yml
    with:
      resource-group: ${{ github.event.inputs.resource-group || 'azure-components-foundry' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  deploy:
    needs: azure-login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then
            pip install poetry
            poetry install
          else
            pip install -r requirements.txt
          fi
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy components
        env:
          AZURE_RESOURCE_GROUP: ${{ github.event.inputs.resource-group || 'azure-components-foundry' }}
          COMPONENT_PATH: ${{ github.event.inputs.component-path }}
          SUBSCRIPTION_ID: ${{ github.event.inputs.subscription-id }}
        run: |
          if [ -n "$SUBSCRIPTION_ID" ]; then
            az account set --subscription "$SUBSCRIPTION_ID"
          fi
          
          if [ -n "$COMPONENT_PATH" ]; then
            echo "Deploying specific component: $COMPONENT_PATH"
            python admin/deploy_components.py --component-path "$COMPONENT_PATH" --resource-group "$AZURE_RESOURCE_GROUP"
          else
            echo "Deploying all modified components"
            python admin/deploy_components.py --resource-group "$AZURE_RESOURCE_GROUP"
          fi